# -*- coding: utf-8 -*-
"""ArcGIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0J4C_tI9xFUBUljI8VyHa_YZ6F1n9II
"""

!pip install arcgis
from arcgis import GIS

user = "user"
mdp = "mdp"
gis = GIS("https://www.arcgis.com", user, mdp)

print(f"Connecté en tant que : {gis.users.me.username}")

hub_sites = gis.content.search(query="type:Hub Site Application", item_type="Hub Site Application")

for i in hub_sites:
    print(f"Nom du site: {i.title}, URL: {i.url}")

#datasets = gis.content.search(query="climate data", item_type="Feature Layer")

#for dataset in datasets:
    #print(f"Titre: {dataset.title}, URL: {dataset.url}")


csv_items = gis.content.search(query="type:CSV", max_items=100)
csv_items

pdf_user_od = gis.content.search(query="type:PDF AND owner:UserOD", max_items=1000)

all_items = gis.content.search(query="owner:UserOD", max_items=1000)
print(f"Nombres d'items de l'utilisateur UserOD: {len(all_items)}")

import os

output_folder = "downloaded_data"
os.makedirs(output_folder, exist_ok=True)

for item in all_items:
        try:

            file_name = item.title.replace(" ", "_") + ".zip"

            output_path = os.path.join(output_folder, file_name)

            item.download(save_path=output_path)
            print(f"Téléchargé : {item.title}")
        except Exception as e:
            print(f"Erreur lors du téléchargement de {item.title} : {e}")

item_1 = all_items[0]
item_1.title

